### ISSUE TITLE
Migrate to Google Identity Services SDK before March 2023

### ISSUE THREAD

**Issue by chrisputnam9** [chrisputnam9/quixer#102]
**References**
- https://developers.google.com/identity/oauth2/web/guides/migration-to-gis
- https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#the_new_way
- https://developers.google.com/docs/api/quickstart/js
- https://developers.google.com/identity/oauth2/web/reference/js-reference
- https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientsettokentokenobject--

**Todo**
- [x] Get sign in / out / state working
- [x] Detect updates to config
- [x] Sync config working
- [x] Test and launch
- [x] Updates to privacy page (if needed)
- [ ] #106
- [ ] #107

**Comment by chrisputnam9** [comment]
Up Next:
 - Keep reviewing https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#the_new_way

**Comment by chrisputnam9** [comment]
Up next: figure out how to store token / maintain sign-in status

**Comment by chrisputnam9** [comment]
https://developers.google.com/docs/api/quickstart/js

**Comment by chrisputnam9** [comment]
https://developers.google.com/identity/oauth2/web/reference/js-reference
